# Generated by Django 5.0.1 on 2024-01-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrugTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_class", models.CharField(max_length=10)),
                ("subdrug", models.CharField(blank=True, max_length=10, null=True)),
                ("description", models.CharField(max_length=255)),
                ("blood", models.BooleanField(default=False)),
                ("urine", models.BooleanField(default=False)),
                ("oral_fluids", models.BooleanField(default=False)),
                ("hair", models.BooleanField(default=False)),
            ],
        ),
    ]
