# Generated by Django 5.0.1 on 2024-01-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drugtest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("drivers_license_number", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name="drugtest",
            options={"ordering": ["drug_class", "subdrug"]},
        ),
    ]
