# Generated by Django 5.0.1 on 2024-02-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drugtest", "0003_drugcategory_drugsubcategory_drugpanel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drugcategory",
            options={"verbose_name_plural": "Drug Categories"},
        ),
        migrations.AlterModelOptions(
            name="drugsubcategory",
            options={"verbose_name_plural": "Drug Sub Categories"},
        ),
        migrations.AlterField(
            model_name="drugsubcategory",
            name="drug_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_categories",
                to="drugtest.drugcategory",
            ),
        ),
    ]
