# Generated by Django 5.0.1 on 2024-02-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drugtest", "0005_service_drugcategory_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="drugcategory",
            name="service",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="drugtest.service",
            ),
            preserve_default=False,
        ),
    ]
