# Generated by Django 5.0.1 on 2024-02-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drugtest", "0006_drugcategory_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drugpanel",
            name="panel_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
